#!/usr/bin/env python3
"""Generate public/data/klimek-quizzes.json. Run from repo root."""
from __future__ import annotations

import json
from pathlib import Path

ORIG = {"kind": "original", "work": "Original NCLEX-style item for this lecture"}


def open_rn(work: str, url: str) -> dict:
    return {
        "kind": "open-rn",
        "work": work,
        "license": "CC BY 4.0",
        "url": url,
    }


def q(qid: str, prompt: str, options: list[str], answer: str, rationale: str, source: dict) -> dict:
    return {
        "id": qid,
        "prompt": prompt,
        "options": [{"key": k, "text": t} for k, t in zip("ABCD", options)],
        "answer": answer,
        "rationale": rationale,
        "source": source,
    }


ABG_SKILLS = open_rn(
    "Open RN Nursing Skills 2e, 11.2 Basic Concepts of Oxygenation",
    "https://wtcs.pressbooks.pub/nursingskills/chapter/11-2-basic-concepts-of-oxygenation/",
)
ABG_FUND = open_rn(
    "Open RN Nursing Fundamentals 2e, 15.5 Acid-Base Balance / 15.8 Learning Activities",
    "https://wtcs.pressbooks.pub/nursingfundamentals/chapter/15-8-learning-activities/",
)
ABG_FUND_15_5 = open_rn(
    "Open RN Nursing Fundamentals 2e, 15.5 Acid-Base Balance",
    "https://wtcs.pressbooks.pub/nursingfundamentals/chapter/15-5-acid-base-balance/",
)
PHARM_DM = open_rn(
    "Open RN Nursing Pharmacology 2e, 9.4 Antidiabetics",
    "https://wtcs.pressbooks.pub/pharmacology2e/chapter/9-4-antidiabetics/",
)
PHARM_DIG = open_rn(
    "Open RN Nursing Pharmacology 2e, 6.7 Cardiac Glycosides",
    "https://wtcs.pressbooks.pub/pharmacology2e/chapter/6-7-cardiac-glycosides/",
)
PHARM_SOT = open_rn(
    "Open RN Nursing Pharmacology 2e, 6.6 Antiarrhythmics",
    "https://wtcs.pressbooks.pub/pharmacology2e/chapter/6-6-antiarrhythmics/",
)
PHARM_CARD = open_rn(
    "Open RN Nursing Pharmacology 2e, Chapter 6 Cardiovascular",
    "https://wtcs.pressbooks.pub/pharmacology2e/chapter/chapter-6/",
)
PHARM_CCB = open_rn(
    "Open RN Nursing Pharmacology 2e, 6.6 Antiarrhythmics (calcium channel blockers)",
    "https://wtcs.pressbooks.pub/pharmacology2e/chapter/6-6-antiarrhythmics/",
)
DELEG = open_rn(
    "Open RN Health Alterations, 1.8 Delegation and Supervision",
    "https://wtcs.pressbooks.pub/healthalts/chapter/1-8-delegation-and-supervision/",
)
LITH = open_rn(
    "Open RN Nursing Mental Health and Community Concepts 2e, 6.4 Mood Stabilizers — Lithium",
    "https://wtcs.pressbooks.pub/nursingmhcc/chapter/6-4-mood-stabilizers/",
)
PTL = open_rn(
    "Open RN Nursing Health Promotion, 19.10 Preterm Labor",
    "https://wtcs.pressbooks.pub/healthpromo/chapter/19-10-preterm-labor/",
)
FHR = open_rn(
    "Open RN Nursing Health Promotion, 10.5 Fetal Heart Rate Monitoring",
    "https://wtcs.pressbooks.pub/healthpromo/chapter/10-5-fetal-heart-rate-monitoring/",
)

quizzes = [
    {
        "lectureId": "a",
        "title": "Acid-Base Principles",
        "questions": [
            q(
                "klimek-a-1",
                "A client's ABG results are pH 7.28, PaCO2 56 mm Hg, and HCO3 24 mEq/L. Which acid-base imbalance should the nurse document?",
                [
                    "Respiratory acidosis",
                    "Respiratory alkalosis",
                    "Metabolic acidosis",
                    "Metabolic alkalosis",
                ],
                "A",
                "Low pH with high PaCO2 and a normal bicarbonate means the lungs are retaining CO2, which is respiratory acidosis. Respiratory alkalosis would show high pH and low PaCO2. Metabolic acidosis would show low HCO3 moving with the low pH. Metabolic alkalosis would show high pH and high HCO3.",
                ABG_FUND_15_5,
            ),
            q(
                "klimek-a-2",
                "Which ABG set is within the expected adult reference range?",
                [
                    "pH 7.32, PaCO2 48 mm Hg, HCO3 20 mEq/L",
                    "pH 7.40, PaCO2 40 mm Hg, HCO3 24 mEq/L",
                    "pH 7.50, PaCO2 30 mm Hg, HCO3 24 mEq/L",
                    "pH 7.28, PaCO2 38 mm Hg, HCO3 16 mEq/L",
                ],
                "B",
                "Adult ABG normals are pH 7.35–7.45, PaCO2 35–45 mm Hg, and HCO3 22–26 mEq/L. Option B is the only fully normal set. A is acidotic with high CO2 and low HCO3. C is alkalotic with low CO2. D is metabolic acidosis.",
                ABG_SKILLS,
            ),
            q(
                "klimek-a-3",
                "A client with COPD is hypoventilating. The nurse should anticipate which ABG change first?",
                [
                    "Decreased PaCO2 and increased pH",
                    "Increased PaCO2 and decreased pH",
                    "Increased HCO3 and increased pH",
                    "Decreased PaO2 with a normal pH only",
                ],
                "B",
                "Hypoventilation causes CO2 to accumulate (hypercapnia). Extra CO2 lowers pH, producing respiratory acidosis. Hyperventilation would lower PaCO2 and raise pH. A high HCO3 with high pH is metabolic alkalosis, not the first change from hypoventilation. Low PaO2 can occur but does not explain the acid-base shift by itself.",
                ABG_SKILLS,
            ),
            q(
                "klimek-a-4",
                "Which finding is an early sign of hypoxia that the nurse should report promptly?",
                [
                    "Clubbing of the fingertips",
                    "Cyanosis of the lips",
                    "Restlessness and agitation",
                    "Loss of consciousness",
                ],
                "C",
                "Restlessness, anxiety, and confusion are early hypoxia signs. Cyanosis and loss of consciousness are late. Clubbing reflects chronic hypoxia, not an acute early change.",
                ABG_SKILLS,
            ),
            q(
                "klimek-a-5",
                "A postoperative client is hyperventilating from pain and anxiety. Which acid-base imbalance is most likely?",
                [
                    "Respiratory acidosis from CO2 retention",
                    "Respiratory alkalosis from blowing off CO2",
                    "Metabolic acidosis from lactic acid buildup",
                    "Metabolic alkalosis from gastric losses",
                ],
                "B",
                "Overventilating blows off CO2, so PaCO2 falls and pH rises (respiratory alkalosis). Underventilating would retain CO2 and cause respiratory acidosis. Metabolic acidosis is not the first result of anxiety hyperventilation. Metabolic alkalosis is associated with vomiting or suction, not fast breathing.",
                ORIG,
            ),
            q(
                "klimek-a-6",
                "A client with diabetic ketoacidosis is breathing with deep, rapid respirations. What is the physiologic purpose of this pattern?",
                [
                    "To retain carbon dioxide and raise pH",
                    "To blow off carbon dioxide and compensate for metabolic acidosis",
                    "To increase bicarbonate production by the lungs",
                    "To correct hypoxemia caused by pneumonia",
                ],
                "B",
                "Kussmaul respirations compensate for metabolic acidosis by exhaling CO2, which helps raise pH. The lungs do not make bicarbonate. This pattern is not primarily a pneumonia response. Retaining CO2 would worsen acidosis.",
                ORIG,
            ),
            q(
                "klimek-a-7",
                "A client has pH 7.52 and HCO3 34 mEq/L with a near-normal PaCO2. Which clinical picture best matches these values?",
                [
                    "Prolonged vomiting with muscle cramps",
                    "Opioid overdose with slow respirations",
                    "Panic attack with numbness of the fingers",
                    "Severe diarrhea with Kussmaul breathing",
                ],
                "A",
                "High pH with high HCO3 is metabolic alkalosis, classically from gastric acid loss (vomiting). Opioid hypoventilation causes respiratory acidosis. A panic attack causes respiratory alkalosis (low PaCO2). Diarrhea causes metabolic acidosis.",
                ORIG,
            ),
            q(
                "klimek-a-8",
                "When arterial pH falls, which potassium change should the nurse anticipate?",
                [
                    "Serum potassium falls as potassium shifts into cells",
                    "Serum potassium rises as potassium shifts out of cells",
                    "Potassium is unrelated to pH",
                    "Only ionized calcium changes; potassium stays the same",
                ],
                "B",
                "In acidosis, hydrogen ions enter cells and potassium leaves, so serum K+ tends to rise. Alkalosis does the opposite (K+ drops). Potassium and pH are tightly linked in acid-base disorders. Calcium can also change, but it does not replace the potassium shift.",
                ORIG,
            ),
            q(
                "klimek-a-9",
                "A client with chronic COPD has pH 7.36, PaCO2 58 mm Hg, and HCO3 32 mEq/L. How should the nurse interpret this ABG?",
                [
                    "Uncompensated respiratory acidosis",
                    "Fully compensated respiratory acidosis",
                    "Uncompensated metabolic alkalosis",
                    "Uncompensated respiratory alkalosis",
                ],
                "B",
                "pH is in the normal (slightly acid) range while CO2 is high and HCO3 is also high, showing renal compensation for chronic CO2 retention. Uncompensated respiratory acidosis would have a low pH and a still-normal HCO3. The high HCO3 is compensation, not a primary metabolic alkalosis. CO2 is high, not low, so this is not alkalosis from hyperventilation.",
                ABG_FUND_15_5,
            ),
            q(
                "klimek-a-10",
                "Which client is the highest priority based on acid-base status?",
                [
                    "pH 7.33 after a mild asthma flare, speaking in full sentences",
                    "pH 7.29 with Kussmaul respirations in new DKA, alert and oriented",
                    "pH 7.18 with decreasing level of consciousness",
                    "pH 7.47 after an anxiety attack, tingling fingers",
                ],
                "C",
                "A pH in the low 7.1s with a falling LOC is immediately life-threatening. Mild acidosis with a talking client is less urgent. DKA needs treatment but this client is still alert. Anxiety alkalosis is uncomfortable but usually not the first priority over a crashing pH.",
                ORIG,
            ),
        ],
    },
    {
        "lectureId": "b",
        "title": "Alcohol",
        "questions": [
            q(
                "klimek-b-1",
                "A client with alcohol use disorder says, “I can stop whenever I want; I just drink to be social.” Which defense mechanism is this?",
                [
                    "Projection",
                    "Denial",
                    "Displacement",
                    "Sublimation",
                ],
                "B",
                "Denial is refusing to accept the reality of a problem. Projection attributes one’s own feelings to others. Displacement shifts feelings onto a safer target. Sublimation channels impulses into acceptable activity.",
                ORIG,
            ),
            q(
                "klimek-b-2",
                "A client with a long alcohol history is confused, ataxic, and has confabulation. Which intervention is essential?",
                [
                    "Fluid restriction to prevent cerebral edema",
                    "Thiamine (vitamin B1) before or with glucose",
                    "High-dose vitamin D and calcium",
                    "Immediate antipsychotic for the confabulation",
                ],
                "B",
                "Wernicke-Korsakoff syndrome is caused by thiamine deficiency; give B1 and do not delay it. Fluid restriction is for SIADH, not this syndrome. Vitamin D is unrelated. Confabulation is a memory gap, not a primary psychosis requiring an antipsychotic first.",
                ORIG,
            ),
            q(
                "klimek-b-3",
                "Which statement correctly distinguishes alcohol withdrawal syndrome (AWS) from delirium tremens (DT)?",
                [
                    "AWS is always life-threatening; DT is uncomfortable but safe",
                    "Every person who stops heavy drinking gets DT within 6 hours",
                    "AWS is common after stopping alcohol; DT is a minority and is life-threatening",
                    "DT occurs only in people who have never had withdrawal before",
                ],
                "C",
                "Most withdrawing clients have AWS, which is not automatically lethal. DT is less common, starts later, and can kill. AWS is not “always” life-threatening. DT does not happen to everyone at 6 hours, and prior withdrawal actually raises DT risk.",
                ORIG,
            ),
            q(
                "klimek-b-4",
                "The nurse is planning care 24 hours after a client’s last drink. The client is anxious and tremulous but oriented. Which room assignment is most appropriate?",
                [
                    "Private room near the nurses’ station, NPO, leather restraints",
                    "Semi-private room, regular diet, no automatic restraints",
                    "Seclusion room with four-point restraints until tremors stop",
                    "ICU bed with an endotracheal tube on standby for all AWS clients",
                ],
                "B",
                "Uncomplicated AWS can usually be managed in a semi-private setting with oral intake. Private room, NPO, and restraints are reserved for DT-level danger. Seclusion and intubation are not default AWS care.",
                ORIG,
            ),
            q(
                "klimek-b-5",
                "A client overdoses on a stimulant (“upper”). Which findings should the nurse expect?",
                [
                    "Bradycardia, hypothermia, and pinpoint pupils",
                    "Respiratory depression and coma",
                    "Tachycardia, restlessness, and hyperreflexia",
                    "Flaccid muscles and absent bowel sounds",
                ],
                "C",
                "Uppers make everything go up: HR, reflexes, mood, and seizure risk. Bradycardia, coma, flaccid muscles, and respiratory depression are downer-overdose pictures.",
                ORIG,
            ),
            q(
                "klimek-b-6",
                "A newborn’s mother used a long-acting opioid throughout pregnancy. At 24 hours of life the infant is irritable with a high-pitched cry. What does this most likely represent?",
                [
                    "Intoxication from residual opioid (too much downer)",
                    "Withdrawal (too little downer), so signs go up",
                    "Wernicke encephalopathy",
                    "Physiologic jaundice",
                ],
                "B",
                "After birth the infant no longer receives the opioid, so withdrawal makes signs go up (irritability, shrill cry). Intoxication would look sedated. Wernicke is a thiamine problem in adults. Jaundice does not cause a high-pitched cry by itself.",
                ORIG,
            ),
            q(
                "klimek-b-7",
                "Disulfiram teaching is effective when the client states which of the following?",
                [
                    "“I can have wine if I wait 2 hours after the pill.”",
                    "“I must avoid alcohol, including hidden sources, for about 2 weeks after stopping the drug.”",
                    "“Mouthwash and aftershave are safe because they are not drinks.”",
                    "“This drug reduces my craving so alcohol will not make me sick.”",
                ],
                "B",
                "Disulfiram causes a sick reaction with alcohol and stays a risk for about 2 weeks after the last dose. Hidden alcohol (mouthwash, aftershave) counts. It is aversion therapy, not a craving-blocker that makes drinking safe.",
                ORIG,
            ),
            q(
                "klimek-b-8",
                "Which overdose is most likely to cause respiratory arrest?",
                [
                    "Cocaine overdose",
                    "Caffeine overdose",
                    "Benzodiazepine overdose",
                    "Amphetamine overdose",
                ],
                "C",
                "Downer overdose depresses respiration. Cocaine, caffeine, and amphetamines are uppers; their overdose risk is seizure more than apnea.",
                ORIG,
            ),
            q(
                "klimek-b-9",
                "Which medications are commonly part of care for both AWS and DT?",
                [
                    "Antihypertensive, benzodiazepine, and thiamine",
                    "Insulin, metformin, and potassium",
                    "Heparin, warfarin, and vitamin K",
                    "Levothyroxine, iodine, and beta blocker",
                ],
                "A",
                "Both AWS and DT are treated with a downer (often a benzo), BP support as needed, and B1 to prevent Wernicke. Diabetes, anticoagulation, and thyroid drugs are not the core withdrawal bundle.",
                ORIG,
            ),
            q(
                "klimek-b-10",
                "A client withdrawing from a benzodiazepine is at greatest risk for which complication?",
                [
                    "Pinpoint pupils and constipation",
                    "Seizure because the nervous system is no longer down",
                    "Immediate Wernicke-Korsakoff without alcohol history",
                    "Hypoglycemia from excess insulin release",
                ],
                "B",
                "Withdrawal from a downer lets the nervous system rebound up, so seizure is the feared event. Pinpoint pupils fit opioid intoxication. Wernicke is thiamine/alcohol. Insulin release is not the primary benzo-withdrawal mechanism.",
                ORIG,
            ),
        ],
    },
    {
        "lectureId": "c",
        "title": "Cardiac and Pharm",
        "questions": [
            q(
                "klimek-c-1",
                "Before giving digoxin, the nurse assesses an apical pulse of 52/min. What is the priority action?",
                [
                    "Give the dose; bradycardia means the drug is working",
                    "Hold the dose and notify the provider",
                    "Double the next dose to compensate",
                    "Switch the route from oral to IV immediately",
                ],
                "B",
                "Digoxin has a negative chronotropic effect. If the apical rate is under 60/min, hold the dose and call the provider unless other parameters are ordered. Giving or doubling the dose risks toxicity. Changing route is not an independent nursing decision here.",
                PHARM_DIG,
            ),
            q(
                "klimek-c-2",
                "A client on digoxin reports nausea and yellow-green visual halos. Potassium is 3.1 mEq/L. What should the nurse do first?",
                [
                    "Give the scheduled digoxin with a snack",
                    "Withhold digoxin, check the apical pulse, and notify the provider",
                    "Encourage a high-fiber diet and reassess in 8 hours",
                    "Administer a PRN antiemetic only and continue the drug",
                ],
                "B",
                "GI symptoms plus visual changes suggest digoxin toxicity, and hypokalemia increases that risk. Hold the drug, assess the pulse, and notify the provider. An antiemetic or diet change does not treat toxicity.",
                PHARM_DIG,
            ),
            q(
                "klimek-c-3",
                "A client takes sublingual nitroglycerin for angina. After the first dose, pain is unchanged at 5 minutes. What is the correct teaching?",
                [
                    "Take a second dose and call emergency services if pain continues after three doses",
                    "Wait 30 minutes before another tablet",
                    "Swallow the next tablet with water for faster action",
                    "Stop all doses if a headache occurs, even if chest pain remains",
                ],
                "A",
                "Reassess pain after about 5 minutes and repeat up to three sublingual doses; if pain persists, activate emergency care. Swallowing SL NTG delays effect. Headache is common from vasodilation and is not a reason to ignore ongoing chest pain.",
                PHARM_CARD,
            ),
            q(
                "klimek-c-4",
                "Sotalol is being started for a life-threatening arrhythmia. Which monitoring is essential because of a boxed warning?",
                [
                    "Serum amylase every 4 hours",
                    "QTc interval after doses during initiation",
                    "Hourly capillary blood glucose only",
                    "Peak and trough vancomycin levels",
                ],
                "B",
                "Sotalol prolongs the QT interval and can cause drug-induced arrhythmias; QTc is checked 2–4 hours after doses when therapy starts. Amylase, isolated glucose checks, and vancomycin levels are not the boxed-warning focus.",
                PHARM_SOT,
            ),
            q(
                "klimek-c-5",
                "Diltiazem is ordered for a client with SVT. The nurse should withhold the dose and call the provider for which finding?",
                [
                    "Blood pressure 88/54 mm Hg",
                    "Heart rate 102/min",
                    "Mild ankle edema that is chronic",
                    "Atrial fibrillation with a rapid rate",
                ],
                "A",
                "Calcium channel blockers are not given to hypotensive clients; they can worsen BP and heart block. Tachycardia/SVT or AF with RVR may be indications. Mild chronic edema is a known effect to monitor, not an automatic hold for SVT treatment if BP is adequate.",
                PHARM_CCB,
            ),
            q(
                "klimek-c-6",
                "Which statement about calcium channel blockers is accurate for exam-style cardiac use?",
                [
                    "They are first-line drugs to convert ventricular fibrillation",
                    "They calm the heart and are useful for rate control in SVT and atrial arrhythmias",
                    "They must be given in asystole before epinephrine",
                    "They increase contractility like digoxin",
                ],
                "B",
                "CCBs (including -dipines, verapamil, diltiazem) decrease HR and BP and help SVT/atrial rate control. They are not VF or asystole drugs and they are negative inotropes, not digoxin-like boosters of squeeze.",
                ORIG,
            ),
            q(
                "klimek-c-7",
                "A chest tube to water seal has continuous bubbling. What does this most likely indicate?",
                [
                    "Normal tidaling with respiration",
                    "An air leak that needs assessment of connections and the insertion site",
                    "The collection chamber is full and should be emptied hourly",
                    "The client needs immediate clamping of the tube for 8 hours",
                ],
                "B",
                "Continuous bubbling in the water seal suggests a leak. Intermittent bubbling with a pneumothorax can be expected; tidaling is rise/fall with breathing. Do not routinely clamp a chest tube for hours. The collection chamber is not emptied like a Foley.",
                ORIG,
            ),
            q(
                "klimek-c-8",
                "Which congenital heart defect is cyanotic and needs surgical attention rather than a “watch and wait” VSD-type plan?",
                [
                    "Patent ductus arteriosus that is closing",
                    "Ventricular septal defect with a small murmur",
                    "Tetralogy of Fallot",
                    "Atrial septal defect in an asymptomatic school-age child",
                ],
                "C",
                "Tetralogy of Fallot is a TRouBLe (cyanotic, right-to-left) defect. Small VSD, ASD, and many PDAs are acyanotic left-to-right lesions that may be observed.",
                ORIG,
            ),
            q(
                "klimek-c-9",
                "A client is in asystole. After starting CPR, which medication is the priority?",
                [
                    "Adenosine 6 mg rapid IV push",
                    "Epinephrine",
                    "Sotalol PO",
                    "Diltiazem infusion",
                ],
                "B",
                "Asystole is treated with CPR and epinephrine (atropine may also be used). Adenosine is for SVT. Oral sotalol and diltiazem are not asystole drugs.",
                ORIG,
            ),
            q(
                "klimek-c-10",
                "Which rhythm is the highest priority to defibrillate?",
                [
                    "Sinus bradycardia at 52/min in a sleeping athlete",
                    "Occasional PVCs in a client on a telemetry unit",
                    "Pulseless ventricular fibrillation",
                    "First-degree AV block with a PR of 0.22 seconds",
                ],
                "C",
                "Pulseless VF is a shockable lethal rhythm. Sleeping bradycardia, rare PVCs, and first-degree block are lower priority and are not defibrillated.",
                ORIG,
            ),
        ],
    },
    {
        "lectureId": "d",
        "title": "Canes, Crutches, Walkers & Psych",
        "questions": [
            q(
                "klimek-d-1",
                "How should axillary crutches be fitted?",
                [
                    "Pads pressing firmly into the axilla to bear all weight",
                    "About 2–3 finger widths between the axilla and the pad, weight through the hands",
                    "Handgrips at the shoulders so elbows are locked",
                    "Crutch tips 18 inches in front of the toes at rest",
                ],
                "B",
                "Leave 2–3 finger widths under the axilla; body weight goes through the hands, not the armpits (nerve injury risk). Elbows should be slightly flexed. Tips sit slightly in front and lateral, not 18 inches straight ahead.",
                ORIG,
            ),
            q(
                "klimek-d-2",
                "A client with even bilateral weakness is learning crutch walking. Which gait is most appropriate?",
                [
                    "Three-point gait (both crutches with the weak leg, then the strong leg)",
                    "Two-point gait (right crutch with left foot, then left crutch with right foot)",
                    "Swing-through gait only",
                    "Four-point gait is never used for weakness",
                ],
                "B",
                "Two-point (and four-point) gaits are for even/bilateral weakness. Three-point is for one weak or non-weight-bearing leg. Swing-through is for non-weight-bearing or braced legs, not the default for mild even weakness.",
                ORIG,
            ),
            q(
                "klimek-d-3",
                "Which teaching about stairs and crutches is correct?",
                [
                    "Lead with the weak leg going up and the strong leg going down",
                    "Up with the good, down with the bad",
                    "Always move the crutches last on both up and down",
                    "Hop both feet together on every stair",
                ],
                "B",
                "Going up, the strong leg leads; going down, the weak leg (and crutches) go first. The opposite pattern is unsafe. Crutches move with the weak side on stairs.",
                ORIG,
            ),
            q(
                "klimek-d-4",
                "A client with left-leg weakness is prescribed a cane. Where should the cane be held?",
                [
                    "On the weak (left) side",
                    "On the strong (right) side",
                    "Alternating hands each day",
                    "In both hands like a walker",
                ],
                "B",
                "Hold the cane on the strong side so it supports the weak leg during stance. Holding it on the weak side reduces support. A cane is one-handed, not a walker.",
                ORIG,
            ),
            q(
                "klimek-d-5",
                "Correct walker use is demonstrated when the client:",
                [
                    "Picks the walker up, sets it down, then walks to it",
                    "Rocks the walker forward on the back legs while leaning",
                    "Ties belongings to the front bar so they swing",
                    "Uses the walker on stairs without a second person",
                ],
                "A",
                "Pick it up, set it down, walk to it. Rocking or hanging bags can tip the walker. Walkers are not for stairs.",
                ORIG,
            ),
            q(
                "klimek-d-6",
                "A client with schizophrenia says, “The FBI planted a chip in my tooth.” What is the best first response?",
                [
                    "“That is not true. Stop talking about it.”",
                    "“I know you feel afraid. I do not hear evidence of a chip, and you are safe here.”",
                    "“Tell me more details so we can find the chip.”",
                    "“You will be secluded until you admit this is a lie.”",
                ],
                "B",
                "For functional psychosis: acknowledge feeling, present reality, and set limits if needed. Arguing or exploring the delusion as fact reinforces it. Punishment/seclusion is not the first communication tool.",
                ORIG,
            ),
            q(
                "klimek-d-7",
                "A client with Alzheimer disease is looking for a deceased spouse. What is the priority approach?",
                [
                    "Orient firmly to the death every 5 minutes",
                    "Redirect to a safe, comforting activity",
                    "Present reality until the client agrees",
                    "Agree that the spouse is in the next room",
                ],
                "B",
                "Dementia clients cannot learn reality the way functional psychosis can; redirect. Repeated confrontation increases distress. Lying that the spouse is nearby is not the goal; comfort and safety are.",
                ORIG,
            ),
            q(
                "klimek-d-8",
                "A client with a UTI becomes acutely confused and sees “bugs on the wall.” After safety, what is the priority?",
                [
                    "Start a long-term antipsychotic for schizophrenia",
                    "Treat the underlying cause (infection) and reassure that the experience will pass",
                    "Teach insight-oriented psychotherapy tonight",
                    "Ignore the confusion because it is expected aging",
                ],
                "B",
                "Delirium is acute and often medical; treat the cause and reassure. This is not a new schizophrenia diagnosis. Insight work is not the acute priority. Acute confusion is not “normal aging.”",
                ORIG,
            ),
            q(
                "klimek-d-9",
                "A client points to a fire extinguisher and says, “That red box is a bomb.” This is best classified as:",
                [
                    "A hallucination (no sensory referent)",
                    "An illusion (misinterpretation of a real object)",
                    "Loose association",
                    "A flight of ideas",
                ],
                "B",
                "An illusion misreads a real stimulus. A hallucination has no external object. Loose association and flight of ideas are thought-process problems, not this misperception.",
                ORIG,
            ),
            q(
                "klimek-d-10",
                "Which client statement is an example of a hallucination?",
                [
                    "“The IV pump alarm is a police siren.”",
                    "“I hear a voice telling me I am worthless when the room is quiet.”",
                    "“My thoughts jump from cars to soup to the president.”",
                    "“People on TV are sending me coded messages.”",
                ],
                "B",
                "Hearing a voice with no external sound is a hallucination. The IV-pump example is an illusion. Jumping topics is flight of ideas. TV messages are a delusion.",
                ORIG,
            ),
        ],
    },
    {
        "lectureId": "e",
        "title": "Diabetes",
        "questions": [
            q(
                "klimek-e-1",
                "Which statement about type 1 versus type 2 diabetes is accurate?",
                [
                    "Type 1 is primarily insulin resistance; oral drugs always replace insulin",
                    "Type 1 involves absent insulin production, so insulin is required",
                    "Type 2 never progresses to needing insulin",
                    "Only type 2 can develop diabetic ketoacidosis",
                ],
                "B",
                "Type 1 is autoimmune beta-cell failure; insulin is essential. Type 2 is mainly resistance and may later need insulin. DKA is classic in type 1 but can occur in type 2 as well; it is not exclusive to type 2.",
                PHARM_DM,
            ),
            q(
                "klimek-e-2",
                "Insulin lispro is ordered with breakfast. When should the nurse administer it?",
                [
                    "Within 15 minutes before the meal or right after eating",
                    "Two hours before the tray arrives",
                    "At bedtime only",
                    "Only if the blood glucose is below 70 mg/dL",
                ],
                "A",
                "Rapid-acting (prandial) insulin is given within 15 minutes of a meal because onset is fast. Giving it long before food or when the client is already hypoglycemic risks a dangerous drop. It is not a bedtime basal insulin.",
                PHARM_DM,
            ),
            q(
                "klimek-e-3",
                "Regular insulin is given subcutaneously at 0730. When is the client at highest risk for hypoglycemia related to peak effect?",
                [
                    "About 15 minutes later",
                    "About 3 hours later",
                    "About 24 hours later with no peak",
                    "Immediately, because regular insulin has no onset delay",
                ],
                "B",
                "Open RN lists regular insulin peak around 3 hours (onset ~30 minutes, duration ~8 hours). Rapid-acting peaks sooner. Long-acting insulins lack a pronounced peak. Regular does have an onset delay of about 30 minutes.",
                PHARM_DM,
            ),
            q(
                "klimek-e-4",
                "Which action is correct when mixing NPH with regular insulin?",
                [
                    "Draw NPH first, then regular, because NPH is clear",
                    "Draw regular (clear) first, then NPH (cloudy); roll NPH to resuspend",
                    "Shake both vials hard until foamy",
                    "Mix glargine into the same syringe with NPH",
                ],
                "B",
                "NPH is cloudy and is rolled, not shaken hard. Clear regular is drawn before cloudy NPH. Glargine must not be mixed with other insulins.",
                PHARM_DM,
            ),
            q(
                "klimek-e-5",
                "Why must insulin glargine not be mixed in the same syringe with other insulins?",
                [
                    "It has a relatively peakless 24-hour profile and mixing alters that action",
                    "It is the only insulin given intravenously",
                    "It is cloudy and will precipitate regular insulin",
                    "It must be given within 15 minutes of meals only",
                ],
                "A",
                "Long-acting glargine/detemir are clear, peakless basal insulins given subcutaneously and not mixed. They are not meal-only rapid insulins and are not the standard IV insulin (regular is).",
                PHARM_DM,
            ),
            q(
                "klimek-e-6",
                "A conscious client has blood glucose 58 mg/dL and is sweaty and shaky. What is the nurse’s first action?",
                [
                    "Give 15 grams of rapid carbohydrate such as 4 oz fruit juice",
                    "Give NPH insulin to stabilize the glucose",
                    "Start a metformin tablet",
                    "Wait 30 minutes to recheck before treating",
                ],
                "A",
                "Hypoglycemia below 70 mg/dL in a client who can swallow is treated with about 15 g of fast carbohydrate. Insulin or metformin would worsen hypoglycemia. Do not delay treatment.",
                PHARM_DM,
            ),
            q(
                "klimek-e-7",
                "A client with diabetes is unresponsive with glucose 38 mg/dL and no IV access. Which medication should the nurse prepare?",
                [
                    "Subcutaneous insulin lispro",
                    "Glucagon IM or subcutaneous, then carbohydrate when safe to swallow",
                    "Oral glipizide",
                    "IV potassium chloride first",
                ],
                "B",
                "Severe hypoglycemia with inability to swallow is treated with glucagon (or IV dextrose if access exists). Insulin and sulfonylureas lower glucose further. Potassium is not the first rescue drug for this scene.",
                PHARM_DM,
            ),
            q(
                "klimek-e-8",
                "Which features best distinguish DKA from hyperosmolar hyperglycemic state (HHS/HHNK)?",
                [
                    "DKA has ketones and acidosis, more often in type 1; HHS is extreme hyperglycemia without significant ketones, more often in type 2",
                    "HHS always has Kussmaul respirations; DKA never does",
                    "Only HHS needs insulin; DKA is treated with oral fluids alone",
                    "DKA occurs only after age 65; HHS occurs only in children",
                ],
                "A",
                "DKA = ketosis/acidosis, classically type 1. HHS = very high glucose, dehydration, little ketosis, classically type 2. Kussmaul is a DKA compensation. Both need fluids and usually insulin. Age patterns are opposite of option D.",
                ORIG,
            ),
            q(
                "klimek-e-9",
                "Why should the nurse monitor potassium in a client receiving insulin?",
                [
                    "Insulin shifts potassium into cells and can cause hypokalemia",
                    "Insulin always raises serum potassium within minutes",
                    "Potassium is unaffected by insulin",
                    "Insulin binds potassium in the gut",
                ],
                "A",
                "Insulin drives potassium intracellularly; untreated hypokalemia can cause dysrhythmias. Insulin does not raise serum K+ or bind it in the gut.",
                PHARM_DM,
            ),
            q(
                "klimek-e-10",
                "A client taking metformin is scheduled for a CT scan with iodinated contrast. What is the priority teaching?",
                [
                    "Double the metformin dose the morning of the scan",
                    "Metformin is often held around contrast because of kidney injury and lactic acidosis risk",
                    "Metformin must be given IV during the scan",
                    "Contrast has no interaction with metformin",
                ],
                "B",
                "Metformin is contraindicated with significant kidney disease and is typically stopped around iodinated contrast to reduce lactic acidosis risk. Do not double the dose or give it IV for a scan.",
                PHARM_DM,
            ),
        ],
    },
    {
        "lectureId": "f",
        "title": "Psych Pharm & Hernias",
        "questions": [
            q(
                "klimek-f-1",
                "A client starts a first-generation phenothiazine antipsychotic. Which teaching about onset is correct?",
                [
                    "Mood will fully normalize in 30 minutes",
                    "It is a major tranquilizer; large doses treat psychosis, and effects build over days to weeks",
                    "It is only used as a one-time sleep aid and never long term",
                    "It has no neurologic side effects",
                ],
                "B",
                "Phenothiazines (many end in -zine) are major tranquilizers used in larger doses for psychosis. They are not instant mood cures, not “no neuro effects” (think ABCDEFG: anticholinergic, blur, constipation, drowsiness, EPS, photosensitivity, agranulocytosis). They can be used longer than one night.",
                ORIG,
            ),
            q(
                "klimek-f-2",
                "The therapeutic serum lithium level the nurse should expect is:",
                [
                    "0.1–0.3 mEq/L",
                    "0.6–1.2 mEq/L",
                    "2.5–3.5 mEq/L",
                    "4.0–5.0 mEq/L",
                ],
                "B",
                "Open RN lists the therapeutic lithium range as 0.6–1.2 mEq/L, drawn 10–12 hours after the last dose. Lower is subtherapeutic; 2.5+ is a medical emergency even if the client looks well.",
                LITH,
            ),
            q(
                "klimek-f-3",
                "Which cluster is an early sign of lithium toxicity?",
                [
                    "Nausea, vomiting, diarrhea, thirst, polyuria, and fine tremor",
                    "Coarse tremor, ataxia, severe hypotension, and clonic movements only",
                    "Agranulocytosis and a sore throat only",
                    "Torsades de pointes from QT prolongation only",
                ],
                "A",
                "Early toxicity (<1.5 mEq/L) includes GI upset, thirst, polyuria, slurred speech, weakness, and fine tremor. Coarse tremor, ataxia, and seizures are later/severe. Agranulocytosis is clozapine. QT risk is more ziprasidone/sotalol.",
                LITH,
            ),
            q(
                "klimek-f-4",
                "Which instruction is appropriate for a client starting lithium?",
                [
                    "Restrict fluids to 500 mL/day to keep the level high",
                    "Aim for about 1.5–3 L of water daily and avoid NSAIDs, which can raise lithium levels",
                    "Take NSAIDs daily to protect the kidneys",
                    "Skip blood tests after the first week",
                ],
                "B",
                "Recommended intake is 1.5–3 L/day. NSAIDs can increase lithium levels. Dehydration and fluid restriction raise toxicity risk. Levels must be monitored regularly.",
                LITH,
            ),
            q(
                "klimek-f-5",
                "A client on a MAOI should be taught to avoid which foods?",
                [
                    "Fresh apples and steamed broccoli",
                    "Aged cheese, smoked meats, and other high-tyramine foods",
                    "White rice and skinless chicken",
                    "All carbohydrates",
                ],
                "B",
                "Tyramine plus a MAOI can cause hypertensive crisis. Fresh produce and plain chicken/rice are generally fine. Carbohydrates as a class are not banned.",
                ORIG,
            ),
            q(
                "klimek-f-6",
                "Fluoxetine is ordered once daily. Which administration time is best and why?",
                [
                    "At bedtime, because it is highly sedating for everyone",
                    "In the morning, because it can cause insomnia",
                    "Only with an MAOI to boost effect",
                    "Once weekly crushed into hot tea",
                ],
                "B",
                "SSRIs like fluoxetine often cause insomnia, so they are given before noon. Combining with a MAOI risks serotonin syndrome. It is not routinely a bedtime sedative.",
                ORIG,
            ),
            q(
                "klimek-f-7",
                "Which teaching is correct for hiatal hernia symptom control?",
                [
                    "High-Fowler after meals, higher fluids, and higher carbohydrate meals to empty the stomach faster",
                    "Lie flat after meals and restrict all fluids",
                    "Increase protein and lie on the left side to slow emptying",
                    "Treat it the same as dumping syndrome",
                ],
                "A",
                "Hiatal hernia: want faster emptying so the stomach is not full when lying (high HOB, high fluids, high carbs). Dumping syndrome is the opposite (low HOB, low fluids with meals, low carbs, high protein). Lying flat after meals worsens reflux/hernia symptoms.",
                ORIG,
            ),
            q(
                "klimek-f-8",
                "A client after gastric surgery has diaphoresis, tachycardia, and abdominal cramping 20 minutes after meals. Which teaching is appropriate?",
                [
                    "Drink a large glass of water with every bite",
                    "Lie down after meals, restrict fluids with food, and increase protein",
                    "Sit high-Fowler and eat extra simple sugars",
                    "Skip meals and take phenothiazines instead",
                ],
                "B",
                "Dumping syndrome: slow emptying (lie down, low fluids with meals, low simple carbs, higher protein). Extra water and sweets worsen dumping. Antipsychotics are not the treatment.",
                ORIG,
            ),
            q(
                "klimek-f-9",
                "Benzodiazepines used as minor tranquilizers should be taught as:",
                [
                    "Safe to stop suddenly after 6 months of daily use",
                    "Useful for short-term (about 2–4 weeks) because of dependence risk",
                    "The only lifelong treatment for schizophrenia",
                    "Free of sedation or withdrawal seizures",
                ],
                "B",
                "Benzos work quickly but are intended short-term; long use brings dependence and withdrawal seizures if stopped abruptly. They are not antipsychotic maintenance for schizophrenia.",
                ORIG,
            ),
            q(
                "klimek-f-10",
                "A client starts a tricyclic antidepressant. What should the nurse teach about timing of benefit?",
                [
                    "Full effect in 15 minutes, like nitroglycerin",
                    "Mood lift may take 2–4 weeks; drowsiness and anticholinergic effects can start sooner",
                    "If there is no change in 48 hours, the drug has failed",
                    "Tricyclics have no cardiac risk in overdose",
                ],
                "B",
                "TCAs take weeks for antidepressant effect while side effects (dry mouth, drowsiness) appear earlier. They are dangerous in overdose (cardiac). Failure is not judged at 48 hours.",
                ORIG,
            ),
        ],
    },
    {
        "lectureId": "g",
        "title": "Endocrine",
        "questions": [
            q(
                "klimek-g-1",
                "A client with Graves disease is most likely to show which cluster?",
                [
                    "Weight gain, bradycardia, and cold intolerance",
                    "Weight loss, heat intolerance, and tachycardia",
                    "Bronze skin and craving salt",
                    "Moon face and buffalo hump",
                ],
                "B",
                "Hyperthyroidism is a high-metabolism state. Hypothyroidism is the opposite. Bronze skin/salt craving is Addison. Moon face is Cushing.",
                ORIG,
            ),
            q(
                "klimek-g-2",
                "Which findings suggest thyroid storm after thyroid surgery?",
                [
                    "Hypothermia, bradycardia, and coma only",
                    "Very high fever, extreme hypertension/tachycardia, and delirium",
                    "Trousseau sign and stridor from hypocalcemia only",
                    "Polyuria and dilute urine from ADH block",
                ],
                "B",
                "Thyroid storm is an extreme hypermetabolic crisis (fever, high BP/HR, psychosis). Hypothermia is myxedema. Tetany/stridor is hypocalcemia after parathyroid removal. Polyuria from ADH block is lithium/DI, not thyroid storm.",
                ORIG,
            ),
            q(
                "klimek-g-3",
                "After a total thyroidectomy, which assessment is the highest priority in the first 12 hours besides airway/hemorrhage?",
                [
                    "Chvostek or Trousseau signs from hypocalcemia",
                    "Moon face from sudden cortisol excess",
                    "Ketones in the urine",
                    "A positive Brudzinski sign",
                ],
                "A",
                "Total thyroidectomy often takes parathyroids, so calcium can crash (tetany, laryngospasm). Cushingoid face, ketones, and meningeal signs are not the classic early total-thyroidectomy issues.",
                ORIG,
            ),
            q(
                "klimek-g-4",
                "After a subtotal (partial) thyroidectomy, the nurse watches most closely for:",
                [
                    "Lifelong hypocalcemia as the first concern",
                    "Thyroid storm because remaining tissue can dump hormone",
                    "Addisonian crisis",
                    "Diabetes insipidus",
                ],
                "B",
                "Partial thyroidectomy leaves tissue that can release hormone (storm risk). Total thyroidectomy is the bigger hypocalcemia risk. Addison and DI are other endocrine axes.",
                ORIG,
            ),
            q(
                "klimek-g-5",
                "A client with myxedema is scheduled for surgery. Which order should the nurse question?",
                [
                    "Give the morning levothyroxine with a sip of water",
                    "Hold thyroid hormone because the client is NPO",
                    "Use a warming blanket for hypothermia",
                    "Monitor for respiratory depression with sedatives",
                ],
                "B",
                "Never hold thyroid replacement in hypothyroidism; these clients already have a low metabolic rate and do poorly if sedated or under-replaced. Warming and caution with sedatives are appropriate.",
                ORIG,
            ),
            q(
                "klimek-g-6",
                "Addison disease is best described as:",
                [
                    "Over-secretion of adrenal steroids",
                    "Under-secretion of adrenal steroids; risk of shock with stress",
                    "Excess ADH with water intoxication",
                    "Excess growth hormone in adulthood",
                ],
                "B",
                "Addison is adrenal insufficiency (need steroids, high risk of crisis with stress). Cushing is over-secretion. SIADH is ADH excess. Acromegaly is GH excess.",
                ORIG,
            ),
            q(
                "klimek-g-7",
                "A client with Addison disease has vomiting, fever, and hypotension after a viral illness. What is the priority?",
                [
                    "Hold steroids until cultures return",
                    "Treat Addisonian crisis: shock care and steroid replacement",
                    "Give a loop diuretic for fluid overload",
                    "Start radioactive iodine",
                ],
                "B",
                "Stress plus vomiting can precipitate crisis; they need fluids/pressors as ordered and steroids, not a hold. They are volume-down, not overloaded. RAI is for hyperthyroid.",
                ORIG,
            ),
            q(
                "klimek-g-8",
                "Which appearance is most consistent with Cushing syndrome?",
                [
                    "Thin extremities, moon face, truncal obesity, and high glucose",
                    "Tan skin, weight loss, and craving salt",
                    "Exophthalmos and a goiter only",
                    "Tetany and a positive Trousseau sign",
                ],
                "A",
                "Cushing = excess steroids (moon face, buffalo hump, truncal obesity, high glucose, immunosuppression, bruising). Tan/salt craving is Addison. Exophthalmos is Graves. Tetany is hypocalcemia.",
                ORIG,
            ),
            q(
                "klimek-g-9",
                "After bilateral adrenalectomy for Cushing disease, the nurse should anticipate:",
                [
                    "No further hormone therapy will ever be needed",
                    "The client will require lifelong steroid replacement and is at Addison-crisis risk if doses are missed",
                    "Immediate radioactive iodine",
                    "A high-sodium restriction forever without steroids",
                ],
                "B",
                "Removing both adrenals creates Addison disease; lifelong replacement is required. RAI is thyroid. Sodium handling depends on mineralocorticoid replacement, not “restriction without steroids.”",
                ORIG,
            ),
            q(
                "klimek-g-10",
                "A client is taking high-dose steroids. Which infection-control teaching is essential?",
                [
                    "Steroids have no effect on immunity",
                    "Report fever early; steroids mask signs of infection and suppress immunity",
                    "Stop steroids the day a fever starts without calling the provider",
                    "Vaccines are never a concern on steroids",
                ],
                "B",
                "Glucocorticoids raise infection risk and hide fever. Abrupt stops can cause crisis. Live vaccines may be restricted; the client should still discuss immunization plans with the provider.",
                ORIG,
            ),
        ],
    },
    {
        "lectureId": "h",
        "title": "Labs",
        "questions": [
            q(
                "klimek-h-1",
                "A serum creatinine of 1.0 mg/dL in an adult is best interpreted as:",
                [
                    "A deadly value requiring dialysis tonight",
                    "Typically a low-priority “A” level reflecting kidney function",
                    "Diagnostic of acute hyperkalemia",
                    "The same as a critical INR",
                ],
                "B",
                "Creatinine ~0.6–1.2 mg/dL is the best indicator of kidney function and is usually not an emergency by itself. It does not equal potassium or INR urgency.",
                ORIG,
            ),
            q(
                "klimek-h-2",
                "A client on warfarin has an INR of 4.8. What is the nurse’s priority?",
                [
                    "Give the next warfarin dose early",
                    "Hold warfarin, assess for bleeding, and notify the provider (often vitamin K)",
                    "Start heparin infusion to “balance” the INR",
                    "Ignore it; INR is only used for heparin",
                ],
                "B",
                "Therapeutic INR on warfarin is often ~2–3; ≥4 is high risk for bleeding. Hold the drug and call. Heparin is monitored with aPTT, not by stacking it onto a high INR.",
                ORIG,
            ),
            q(
                "klimek-h-3",
                "Which potassium result is a deadly emergency requiring a rapid response?",
                [
                    "K+ 3.8 mEq/L",
                    "K+ 4.5 mEq/L",
                    "K+ 6.2 mEq/L with ECG changes",
                    "K+ 3.6 mEq/L in a client eating bananas",
                ],
                "C",
                "Potassium ≥6 mEq/L (especially with ECG changes) is a D-level emergency. Mid-normal values are not.",
                ORIG,
            ),
            q(
                "klimek-h-4",
                "A client’s arterial pH is 6.92. What is the priority action?",
                [
                    "Reassess in 4 hours; this is a mild change",
                    "Treat as a deadly emergency: assess vitals and call the provider/rapid response while addressing the cause",
                    "Give PO sodium bicarbonate and send the client to x-ray unattended",
                    "Document and continue the meal tray",
                ],
                "B",
                "pH in the 6s is immediately life-threatening. Do not delay or leave the client. Oral bicarb and an unattended trip are unsafe.",
                ORIG,
            ),
            q(
                "klimek-h-5",
                "PaCO2 is 58 mm Hg in a client who is still breathing effectively. The best first nursing action is:",
                [
                    "Prepare for immediate intubation as the only option",
                    "Assess respiratory status and purse-lip breathing/ventilation support while notifying the provider",
                    "Give a bolus of potassium",
                    "Start a fluid restriction",
                ],
                "B",
                "CO2 in the 50s is critical but often managed with assessment and ventilation coaching (e.g., pursed-lip) plus provider notification. The 60s with failing ventilation is closer to respiratory failure/intubation. K+ bolus and fluid restriction do not fix CO2.",
                ORIG,
            ),
            q(
                "klimek-h-6",
                "Which oxygenation value is most consistent with respiratory failure needing aggressive intervention?",
                [
                    "PaO2 92 mm Hg, SpO2 97%",
                    "PaO2 78 mm Hg, client speaking in sentences",
                    "PaO2 58 mm Hg with dyspnea and falling SpO2",
                    "SpO2 94% in a client with chronic COPD at their baseline",
                ],
                "C",
                "PaO2 normally 80–100 mm Hg; the 60s with distress is a deadly hypoxia picture. Mid-70s needs assessment and oxygen but may not equal arrest. COPD baselines can be 88–92% SpO2.",
                ABG_SKILLS,
            ),
            q(
                "klimek-h-7",
                "A platelet count of 28,000/mm3 means the nurse should:",
                [
                    "Encourage IM injections and rectal temperatures",
                    "Implement bleeding precautions and notify the provider; this is a high-risk (often “D”) value",
                    "Start heparin to prevent clots",
                    "Treat it as a normal count",
                ],
                "B",
                "Platelets <40,000 (and often <90,000 as critical) mean bleeding risk. Avoid IM/rectal trauma. Heparin would worsen bleeding. 28k is not normal.",
                ORIG,
            ),
            q(
                "klimek-h-8",
                "An absolute neutrophil count (ANC) of 400/mm3 requires which priority?",
                [
                    "Place the client on neutropenic precautions",
                    "Give a live-virus vaccine today",
                    "Send the client to a crowded waiting room",
                    "Stop all hand hygiene because gloves are enough",
                ],
                "A",
                "ANC <500 is severe neutropenia: protect from infection. Live vaccines and crowds are dangerous. Hand hygiene remains essential.",
                ORIG,
            ),
            q(
                "klimek-h-9",
                "Sodium is 150 mEq/L and the client’s only new finding is thirst. How urgent is this compared with sodium 128 mEq/L plus a sudden change in LOC?",
                [
                    "The isolated high sodium is more urgent than a low sodium with LOC change",
                    "Abnormal sodium plus a change in consciousness is the higher priority",
                    "Both are equally non-urgent",
                    "Sodium disorders never affect the brain",
                ],
                "B",
                "Sodium abnormalities become an emergency when LOC changes (safety/seizure risk). Isolated abnormal Na with only thirst is still important but lower than a neuro change. Sodium strongly affects the brain.",
                ORIG,
            ),
            q(
                "klimek-h-10",
                "An elevated BNP is most useful as a marker for which condition?",
                [
                    "Acute myocardial infarction exclusively",
                    "Heart failure (ventricular stretch)",
                    "Hepatitis A",
                    "Hypothyroidism",
                ],
                "B",
                "BNP rises with ventricular stretch/heart failure. It is not the MI gold standard (troponin), not a hepatitis test, and not a TSH substitute. It is often a lower-urgency lab than the five deadly values (pH, K, CO2, O2, platelets).",
                ORIG,
            ),
        ],
    },
    {
        "lectureId": "i",
        "title": "Psych Drugs",
        "questions": [
            q(
                "klimek-i-1",
                "A client on haloperidol develops high fever, lead-pipe rigidity, and autonomic instability. What is the nurse’s interpretation?",
                [
                    "Expected extrapyramidal side effects; give a PRN snack",
                    "Neuroleptic malignant syndrome — a medical emergency",
                    "Serotonin syndrome from too little dopamine",
                    "Agranulocytosis, which always presents with muscle rigidity",
                ],
                "B",
                "NMS is fever + severe rigidity + unstable vitals after antipsychotics. EPS is tremor/dystonia/akathisia without that malignant picture. Serotonin syndrome is more hyperreflexia/clonus with serotonergic drugs. Agranulocytosis is infection from low WBCs, not rigidity.",
                ORIG,
            ),
            q(
                "klimek-i-2",
                "Why is a high fever in an older adult on haloperidol especially concerning?",
                [
                    "Older adults cannot get NMS",
                    "They are at higher NMS risk; fever and rigidity need immediate evaluation",
                    "Fever always means the dose should be doubled",
                    "Haloperidol treats fever",
                ],
                "B",
                "Elderly clients are more sensitive to typical antipsychotics and NMS. Do not increase the dose for fever. Haldol is not an antipyretic.",
                ORIG,
            ),
            q(
                "klimek-i-3",
                "Clozapine requires which laboratory monitoring because of a life-threatening adverse effect?",
                [
                    "Weekly (then periodic) WBC/ANC for agranulocytosis",
                    "Daily amylase only",
                    "Serum lithium levels",
                    "Fasting lipid panel every shift",
                ],
                "A",
                "Clozapine can cause agranulocytosis; WBC/ANC monitoring is mandatory. Lithium levels are for lithium. Lipids matter with some atypicals but not every shift. Amylase is not the clozapine hallmark.",
                ORIG,
            ),
            q(
                "klimek-i-4",
                "A client on sertraline starts St. John’s wort. What is the main risk?",
                [
                    "Severe hypotension from MAOI crisis only",
                    "Serotonin syndrome from excess serotonergic activity",
                    "Complete loss of any antidepressant effect in 10 minutes",
                    "Immediate agranulocytosis",
                ],
                "B",
                "SSRIs plus St. John’s wort (or other serotonergic agents) raise serotonin syndrome risk. MAOI/tyramine is a different crisis. Agranulocytosis is clozapine. Effect loss is not instantaneous from one herb dose in that way.",
                ORIG,
            ),
            q(
                "klimek-i-5",
                "Ziprasidone (Geodon) teaching should include which cardiac caution?",
                [
                    "It has no ECG effects",
                    "It can prolong QT and increase arrhythmia risk",
                    "It is the drug of choice in congenital long-QT syndrome",
                    "It must be combined with sotalol to protect the QT",
                ],
                "B",
                "Ziprasidone prolongs QT. Do not pair QT-prolonging drugs casually. It is not indicated to treat long-QT syndrome.",
                ORIG,
            ),
            q(
                "klimek-i-6",
                "Which cluster suggests serotonin syndrome rather than NMS?",
                [
                    "Lead-pipe rigidity, very high fever, bradyreflexia after a typical antipsychotic",
                    "Hyperreflexia, clonus, diarrhea, and agitation after an SSRI/MAOI combination",
                    "Isolated dry mouth from anticholinergic effect",
                    "A sore throat and ANC of 400 on clozapine",
                ],
                "B",
                "Serotonin syndrome: clonus/hyperreflexia, GI upset, agitation, often after serotonergic combos. NMS is rigid and bradyreflexic. Dry mouth is anticholinergic. Low ANC is agranulocytosis.",
                ORIG,
            ),
            q(
                "klimek-i-7",
                "A client stopped a MAOI yesterday and is due for an SSRI today. What should the nurse do?",
                [
                    "Give both; they cancel each other’s side effects",
                    "Hold the SSRI and clarify the washout period with the provider",
                    "Crush the SSRI into the MAOI dose",
                    "Give a tyramine snack to test safety",
                ],
                "B",
                "MAOIs and SSRIs need a washout to avoid serotonin syndrome. They do not cancel. Tyramine testing is dangerous.",
                ORIG,
            ),
            q(
                "klimek-i-8",
                "EPS (dystonia, Parkinsonism, akathisia) from a typical antipsychotic is usually treated with:",
                [
                    "A bolus of insulin",
                    "An anticholinergic such as benztropine",
                    "A second typical antipsychotic",
                    "Immediate dialysis",
                ],
                "B",
                "Anticholinergics (benztropine, diphenhydramine) treat EPS. Adding another typical or using insulin/dialysis is not EPS care.",
                ORIG,
            ),
            q(
                "klimek-i-9",
                "A client on clozapine reports a sore throat and fever. Priority action?",
                [
                    "Reassure that this is expected dry mouth",
                    "Hold the drug, obtain WBC/ANC, and notify the provider",
                    "Give ibuprofen and the next clozapine dose",
                    "Start St. John’s wort",
                ],
                "B",
                "Fever and sore throat on clozapine may signal agranulocytosis. Hold, labs, provider. Do not keep dosing or add an herb.",
                ORIG,
            ),
            q(
                "klimek-i-10",
                "Which statement about “-zine” typical antipsychotics versus “-zapine” atypicals is most accurate for safety monitoring?",
                [
                    "Typicals: watch EPS/NMS; clozapine-class atypicals: watch WBC",
                    "Neither class needs any lab or neuro checks",
                    "Only atypicals can cause EPS; typicals never do",
                    "NMS occurs only with SSRIs",
                ],
                "A",
                "First-generation (“zines,” haloperidol) are famous for EPS/NMS. Clozapine is famous for agranulocytosis. Typicals cause more EPS, not less. NMS is an antipsychotic emergency, not an SSRI one.",
                ORIG,
            ),
        ],
    },
    {
        "lectureId": "j",
        "title": "Maternity & OB",
        "questions": [
            q(
                "klimek-j-1",
                "A client’s last menstrual period began April 10. Using Naegele’s rule, which estimated due date is correct?",
                [
                    "January 3 of the next year",
                    "January 17 of the next year",
                    "July 10 of the same year",
                    "November 10 of the same year",
                ],
                "B",
                "Naegele: add 7 days and subtract 3 months (or add 9 months + 7 days). April 10 + 7 days = April 17, minus 3 months = January 17. January 3 is 7 days short. July and November are wrong month math.",
                ORIG,
            ),
            q(
                "klimek-j-2",
                "Total recommended weight gain for a client with a normal pre-pregnancy BMI is about:",
                [
                    "10 lb total",
                    "28 lb (about 25–35 lb), with roughly 1 lb/week in the second and third trimesters after ~3 lb in the first",
                    "60 lb in the first trimester alone",
                    "No weight gain is advised",
                ],
                "B",
                "Average gain is about 28 ± 3 lb (25–35 lb for normal BMI). 10 lb is too little; 60 lb in trimester one is excessive. Some gain is expected.",
                ORIG,
            ),
            q(
                "klimek-j-3",
                "At 24 weeks, the fundus is most likely:",
                [
                    "Non-palpable",
                    "At the umbilicus (about 20–22 weeks) plus a few centimeters corresponding to weeks",
                    "At the xiphoid, as at term",
                    "In the pelvis only, as at 8 weeks",
                ],
                "B",
                "Fundus is at the umbilicus around 20–22 weeks; after that, centimeters ≈ weeks (24 cm at 24 weeks). It is not still pelvic or already at the xiphoid.",
                ORIG,
            ),
            q(
                "klimek-j-4",
                "Which is a positive (diagnostic) sign of pregnancy?",
                [
                    "Amenorrhea",
                    "Fetal heart activity on ultrasound",
                    "Nausea",
                    "Urinary frequency",
                ],
                "B",
                "Positive signs are fetal heart tones, visualization of the fetus, and examiner-felt fetal movement. Amenorrhea, nausea, and frequency are presumptive.",
                ORIG,
            ),
            q(
                "klimek-j-5",
                "The first stage of labor is best defined as:",
                [
                    "Delivery of the placenta",
                    "Onset of regular contractions to full cervical dilation",
                    "The hour after the baby is born",
                    "Pushing only, regardless of dilation",
                ],
                "B",
                "Stage 1: labor onset to 10 cm. Stage 2: delivery of the baby. Stage 3: placenta. Stage 4: recovery (about 2 hours). Pushing is stage 2.",
                ORIG,
            ),
            q(
                "klimek-j-6",
                "Late decelerations on the fetal monitor most likely indicate:",
                [
                    "Head compression that is usually benign",
                    "Uteroplacental insufficiency — a nonreassuring pattern needing intervention",
                    "Cord compression that always resolves with amnioinfusion only",
                    "A healthy acceleration",
                ],
                "B",
                "Late decels follow the peak of the contraction and signal placental insufficiency (VEAL CHOP: L = late = placenta). Early = head. Variable = cord. Accelerations are reassuring.",
                FHR,
            ),
            q(
                "klimek-j-7",
                "The nurse notes abrupt, variable-shaped decelerations. What is the usual cause and a first action?",
                [
                    "Head compression; no action needed ever",
                    "Cord compression; reposition the client (often side-lying)",
                    "Maternal fever; start antibiotics immediately without assessment",
                    "Fetal sleep cycle; turn off the monitor",
                ],
                "B",
                "Variables = cord compression; move the mother. Early decels from head compression can be expected in late labor. Fever is a different problem. Never just turn off the monitor.",
                FHR,
            ),
            q(
                "klimek-j-8",
                "Early decelerations that mirror contractions in a client who is 9 cm dilated are usually:",
                [
                    "A sign to prepare for crash cesarean for placental abruption",
                    "Expected from fetal head compression",
                    "Proof of uteroplacental failure",
                    "The same as a prolonged deceleration to 60 bpm for 8 minutes",
                ],
                "B",
                "Early decels are typically benign head compression in active/transition labor. They are not abruption or late-decel pathology. A long, deep deceleration is a different emergency.",
                FHR,
            ),
            q(
                "klimek-j-9",
                "Fetal heart rate is 90 bpm and not recovering. After calling for help, which cluster is the priority (LION-style intrauterine resuscitation)?",
                [
                    "Leave the client supine, stop oxygen, and increase oxytocin",
                    "Left side, stop oxytocin if infusing, IV bolus as ordered, oxygen, notify the provider",
                    "Ambulate in the hall to “wake the baby”",
                    "Give terbutaline and send the client home",
                ],
                "B",
                "Low FHR: side-lying, IV, oxygen, stop Pitocin, notify. Supine position and more oxytocin worsen perfusion. Walking and discharge are unsafe.",
                ORIG,
            ),
            q(
                "klimek-j-10",
                "Fetal station 0 means the presenting part is:",
                [
                    "Floating above the pelvic inlet",
                    "At the ischial spines (engaged)",
                    "Visible on the perineum (crowning)",
                    "In the fundus",
                ],
                "B",
                "Station 0 is engagement at the ischial spines. Negative station is above (floating). Positive station is below, toward crowning. The fundus is the top of the uterus, not station.",
                ORIG,
            ),
        ],
    },
    {
        "lectureId": "k",
        "title": "OB 2",
        "questions": [
            q(
                "klimek-k-1",
                "Preterm labor is defined as regular contractions with cervical change between:",
                [
                    "12 and 16 weeks",
                    "20 and 37 weeks",
                    "38 and 42 weeks",
                    "After 42 weeks only",
                ],
                "B",
                "Preterm labor is 20–37 weeks. Before 20 weeks is a different loss category. 38–42 is term. After 42 is post-term.",
                PTL,
            ),
            q(
                "klimek-k-2",
                "Why are tocolytics given in preterm labor?",
                [
                    "To strengthen contractions for immediate delivery",
                    "To reduce contractions long enough to give antenatal corticosteroids for fetal lung maturity",
                    "To permanently stop all future labors",
                    "To treat neonatal hypoglycemia after birth",
                ],
                "B",
                "Tocolysis buys time (often ~48 hours) for betamethasone/dexamethasone. Oxytocics strengthen labor. Tocolytics are not lifelong and do not treat newborn glucose.",
                PTL,
            ),
            q(
                "klimek-k-3",
                "Terbutaline is infusing for preterm labor. Which finding is a reason to hold the dose and notify the provider?",
                [
                    "Maternal heart rate 128/min",
                    "Mild flushing after nifedipine yesterday",
                    "Fetal heart rate 140/min",
                    "Contractions decreasing from every 3 minutes to every 8 minutes",
                ],
                "A",
                "Terbutaline is a beta agonist; maternal tachycardia >120 is a contraindication/hold. A FHR of 140 is normal. Fewer contractions mean the drug may be working. Flushing is more a nifedipine vasodilator effect.",
                PTL,
            ),
            q(
                "klimek-k-4",
                "A client on magnesium sulfate for preterm labor has absent patellar reflexes and respirations of 10/min. What should the nurse do first?",
                [
                    "Increase the magnesium rate to stop remaining contractions",
                    "Stop the infusion, support respirations, and prepare calcium gluconate as the antidote per protocol",
                    "Give another bolus of magnesium",
                    "Discharge home with oral magnesium",
                ],
                "B",
                "Loss of DTRs and respiratory depression are toxicity. Stop mag, airway support, calcium gluconate. More mag worsens toxicity.",
                PTL,
            ),
            q(
                "klimek-k-5",
                "Why is indomethacin generally avoided as a tocolytic after 32 weeks?",
                [
                    "It causes maternal tachycardia like terbutaline",
                    "It risks premature closure of the fetal ductus arteriosus",
                    "It is an oxytocin analog",
                    "It is the drug of choice after 34 weeks",
                ],
                "B",
                "Indomethacin (NSAID) can close the ductus, so it is used <32 weeks and only briefly. After 34 weeks, tocolysis is usually not justified. It is not an oxytocic.",
                PTL,
            ),
            q(
                "klimek-k-6",
                "Betamethasone is ordered at 29 weeks with likely delivery this week. The nurse explains the purpose is to:",
                [
                    "Stop contractions permanently",
                    "Speed fetal lung maturity by promoting surfactant-related changes",
                    "Treat maternal preeclampsia as a first-line antihypertensive",
                    "Replace neonatal vitamin K at birth",
                ],
                "B",
                "Antenatal corticosteroids (22 weeks to 33+6 if delivery is likely within 7 days) mature fetal lungs. They are not tocolytics, antihypertensives, or vitamin K.",
                PTL,
            ),
            q(
                "klimek-k-7",
                "Which medication is an oxytocic used to stimulate labor, not a tocolytic?",
                [
                    "Nifedipine",
                    "Terbutaline",
                    "Oxytocin (Pitocin)",
                    "Indomethacin",
                ],
                "C",
                "Oxytocin/methergine-class drugs stimulate uterine contraction. Nifedipine, terbutaline, and indomethacin are tocolytics.",
                ORIG,
            ),
            q(
                "klimek-k-8",
                "Methylergonovine is ordered for postpartum hemorrhage. The nurse should withhold it for which finding?",
                [
                    "Blood pressure 168/110 mm Hg",
                    "A boggy fundus that firms with massage",
                    "Lochia rubra on day 1",
                    "Breastfeeding interest",
                ],
                "A",
                "Methergine constricts vessels and is contraindicated in hypertension. A boggy fundus is a reason to treat PPH (after massage). Rubra on day 1 and breastfeeding are expected.",
                ORIG,
            ),
            q(
                "klimek-k-9",
                "A 36-hour-old newborn has jaundice and a bilirubin of 18 mg/dL. This is concerning because:",
                [
                    "Jaundice in the first days of life is always physiologic and ignored",
                    "High bilirubin, especially early, can be pathologic and risk kernicterus",
                    "Bilirubin of 18 is below any treatment threshold",
                    "Only cephalhematoma prevents jaundice",
                ],
                "B",
                "Pathologic jaundice is earlier/higher and can injure the brain (kernicterus). Physiologic jaundice is later and milder. Cephalhematoma can worsen jaundice; it does not prevent it.",
                ORIG,
            ),
            q(
                "klimek-k-10",
                "Two hours after a vaginal birth, the fundus is boggy and displaced to the right. What should the nurse do first?",
                [
                    "Call for an operating room for hysterectomy",
                    "Assist the client to void, then reassess and massage the fundus if still boggy",
                    "Give terbutaline to relax the uterus",
                    "Start magnesium sulfate",
                ],
                "B",
                "A full bladder displaces the uterus and causes atony. Empty the bladder, then massage and oxytocics as ordered. Tocolytics/mag would worsen bleeding. Surgery is not first-line.",
                ORIG,
            ),
        ],
    },
    {
        "lectureId": "l",
        "title": "Prioritization & Delegation",
        "questions": [
            q(
                "klimek-l-1",
                "Which client should the nurse see first?",
                [
                    "Chronic emphysema with usual 2 L oxygen and SpO2 91%",
                    "A client 4 hours after abdominal surgery with new restlessness and a falling blood pressure",
                    "A client with a 2-year history of heart failure awaiting a scheduled oral diuretic",
                    "A client ready for discharge teaching after an uncomplicated appendectomy 3 days ago",
                ],
                "B",
                "Fresh postoperative (especially <12 hours) plus unexpected instability beats chronic expected findings and discharge teaching. Acute and unstable outrank chronic and stable.",
                ORIG,
            ),
            q(
                "klimek-l-2",
                "Among these, who is the most unstable?",
                [
                    "Expected colostomy output in a 2-day post-op client",
                    "A client with COPD whose ABG matches their chronic compensated baseline",
                    "New-onset chest pain in a client admitted for observation",
                    "A client with diabetes whose glucose is 140 mg/dL before lunch",
                ],
                "C",
                "Unexpected acute chest pain is unstable. Expected ostomy drainage, chronic compensated COPD, and a modest pre-lunch glucose are more stable.",
                ORIG,
            ),
            q(
                "klimek-l-3",
                "Which order of priority rules is the best NCLEX approach?",
                [
                    "Age first, then diagnosis name, then whoever complains loudest",
                    "Unstable over stable, acute over chronic, unexpected over expected; tie-break with organ vitality (brain, lung, heart, kidney)",
                    "Always see the client with the most equipment first",
                    "Always see the youngest client first",
                ],
                "B",
                "Prioritize unstable/acute/unexpected. Vital organs help break ties. Age, noise, and gadget count are not the primary rules.",
                ORIG,
            ),
            q(
                "klimek-l-4",
                "Which is one of the five rights of delegation?",
                [
                    "Right task, circumstance, person, directions/communication, and supervision/evaluation",
                    "Right diagnosis, right room, and right visiting hours",
                    "Right overtime and right shift length only",
                    "Right to refuse all documentation",
                ],
                "A",
                "NCSBN/ANA five rights: task, circumstance, person, communication, supervision. The other lists are not the delegation framework.",
                DELEG,
            ),
            q(
                "klimek-l-5",
                "Which task cannot be delegated to an LPN/VN?",
                [
                    "Administering oral antibiotics to a stable client per policy",
                    "Collecting routine data such as a pulse on a stable client",
                    "Performing the admission assessment and creating the nursing care plan independently",
                    "Reinforcing teaching the RN has already planned",
                ],
                "C",
                "LPNs cannot independently do admission/initial postoperative assessments, analyze data into diagnoses, or create/evaluate the care plan. They can collect data, give many meds (not high-risk/titrated), and reinforce RN-planned teaching.",
                DELEG,
            ),
            q(
                "klimek-l-6",
                "Which task is appropriate to assign to UAP?",
                [
                    "Nursing assessment of a reddened sacral area to stage a pressure injury",
                    "Assisting a stable client with a bed bath and reporting skin concerns to the nurse",
                    "Discharge teaching about new warfarin",
                    "Titrating a heparin infusion",
                ],
                "B",
                "UAP can do ADLs for stable clients and report concerns. They cannot perform nursing assessments, client education, or titrate high-risk drips. The RN still assesses the skin.",
                DELEG,
            ),
            q(
                "klimek-l-7",
                "Vital signs may be delegated to assistive personnel when:",
                [
                    "The client is unstable in shock",
                    "The client is stable and the task is routine",
                    "The UAP wants to practice clinical judgment on an ICU admission",
                    "The RN is off the unit and unreachable for the shift",
                ],
                "B",
                "Right circumstance: delegate VS on stable clients. Unstable clients need the licensed nurse. The RN must remain available to supervise. UAP cannot take on clinical judgment.",
                DELEG,
            ),
            q(
                "klimek-l-8",
                "After delegating a task, who remains accountable for the client’s overall outcome?",
                [
                    "Only the UAP who accepted the task",
                    "The licensed nurse who delegated, while the delegatee is responsible for doing the task correctly",
                    "The hospital CEO only",
                    "Nobody, once the words “I delegate” are spoken",
                ],
                "B",
                "The licensed nurse keeps accountability for the client; the delegatee is responsible for the specific activity. Accountability does not vanish.",
                DELEG,
            ),
            q(
                "klimek-l-9",
                "An LPN says an assigned stable client now has new stridor. What should the RN do?",
                [
                    "Tell the LPN to keep the original plan without reassessment",
                    "Reassess personally; a changing condition means delegation may no longer be appropriate",
                    "Ask UAP to decide if intubation is needed",
                    "Ignore stridor because the client was stable at 0700",
                ],
                "B",
                "If the client’s condition changes, the delegatee must report and the RN must reassess and possibly take the task back. UAP cannot make airway decisions. Old stability does not override new stridor.",
                DELEG,
            ),
            q(
                "klimek-l-10",
                "A staff member is about to give a medication by the wrong route. What is the charge nurse’s first action?",
                [
                    "Write a long email after the shift",
                    "Intervene immediately to stop harm, then deal with education/discipline",
                "Ask the UAP if the route “seems fine”",
                    "Ignore it if the staff member is senior",
                ],
                "B",
                "Illegal or immediately harmful acts are stopped first. Inappropriate (not illegal/unsafe) behavior can be approached later. Seniority does not allow a wrong route. UAP do not validate medication routes.",
                ORIG,
            ),
        ],
    },
]

bank = {
    "version": 1,
    "attribution": "Open RN by Chippewa Valley Technical College / WisTech Open, CC BY 4.0.",
    "quizzes": quizzes,
}


def main() -> None:
    out = Path("public/data/klimek-quizzes.json")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(bank, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    counts = [(qz["lectureId"], len(qz["questions"])) for qz in quizzes]
    print(f"Wrote {out} with {len(quizzes)} quizzes: {counts}")
    assert len(quizzes) == 12
    assert all(n == 10 for _, n in counts)
    ids = [item["id"] for qz in quizzes for item in qz["questions"]]
    assert len(ids) == len(set(ids))
    for qz in quizzes:
        for item in qz["questions"]:
            assert item["answer"] in {o["key"] for o in item["options"]}
            assert len(item["options"]) == 4
            assert item["source"]["kind"] in {"open-rn", "original"}


if __name__ == "__main__":
    main()
